"""
Synthea realism layer for the TRF feasibility checker
=====================================================
Chapter 3, Section 3.6 specifies two layers: the feasibility checker (the
load-bearing component) and a realism layer feeding it FHIR-structured
records generated by Synthea.

This module is the realism layer. It replaces the synthetic byte-string
payloads of trf_checker.generate() with real FHIR R4 resources drawn from
Synthea-generated patient bundles, leaving every timing quantity
(t_a, t_r, t_pi, F, sigma, delta) untouched.

The purpose is to establish, by execution rather than assertion, that the
model's results are functions of timing and accessibility alone and do not
depend on payload provenance. If any reported figure changes, the model
reads something it should not.

Cohort: synthea -s 20260915 -cs 20260915 -p 100, FHIR R4 export.
Run:    python synthea_layer.py
"""

import glob
import json
import os

import trf_checker as trf

SYNTHEA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "synthea_run", "output", "fhir")
CLINICAL_TYPES = ("Condition", "Observation", "MedicationRequest",
                  "AllergyIntolerance", "Immunization", "Procedure")


def load_payloads(limit=400, seed=trf.SEED):
    """Extract clinically meaningful resources from Synthea bundles and
    serialise each as a payload. These stand in for the content of an
    exchanged patient summary or the subject of an SPE access."""
    files = sorted(glob.glob(os.path.join(SYNTHEA_DIR, "*.json")))
    if not files:
        raise FileNotFoundError(
            f"No Synthea bundles at {SYNTHEA_DIR}. Generate with:\n"
            f"  java -jar synthea.jar -s 20260915 -cs 20260915 -p 100")
    payloads, meta = [], []
    for path in files:
        with open(path) as fh:
            bundle = json.load(fh)
        for entry in bundle.get("entry", []):
            res = entry.get("resource", {})
            if res.get("resourceType") in CLINICAL_TYPES:
                payloads.append(json.dumps(res, sort_keys=True).encode())
                meta.append((os.path.basename(path).split("_")[0],
                             res["resourceType"]))
                break          # one resource per bundle keeps the mapping 1:1
        if len(payloads) >= limit:
            break
    return payloads, meta, len(files)


def generate_with_synthea(n_primary=100, n_secondary=100, seed=trf.SEED):
    """Identical to trf_checker.generate() in every timing respect; only the
    payload bytes differ."""
    records = trf.generate(n_primary, n_secondary, seed)
    payloads, meta, n_files = load_payloads()
    for rec in records:
        p = payloads[rec.rid % len(payloads)]
        rec.payload = p
        rec.c = trf.commit(p, rec.salt)     # recompute commitment over real payload
        rec.m["doc_category"] = (
            f"PatientSummary/{meta[rec.rid % len(meta)][1]}"
            if rec.sigma == "primary"
            else f"SPE-AccessLog/{meta[rec.rid % len(meta)][1]}")
    return records, n_files, len(payloads)


def main():
    print("=" * 74)
    print("SYNTHEA REALISM LAYER — comparison against constructed payloads".center(74))
    print("=" * 74)

    base = trf.generate()
    real, n_files, n_payloads = generate_with_synthea()
    print(f"\nSynthea bundles read : {n_files}")
    print(f"clinical payloads    : {n_payloads}")
    print(f"records              : {len(real)}")
    print(f"payload bytes (mean) : constructed={sum(len(r.payload) for r in base)//len(base)}"
          f"  synthea={sum(len(r.payload) for r in real)//len(real)}")

    results = {}
    for label, recs in (("constructed", base), ("synthea", real)):
        v1 = {r.rid: trf.check_semantics_I(r) for r in recs}
        n_bad = sum(1 for k in v1 if v1[k])
        tot = sum(len(x) for x in v1.values())
        sec = [r for r in recs if r.sigma == "secondary"]
        cor12 = sum(1 for r in sec if r.t_r == trf.INF and v1[r.rid])
        for r in recs:
            trf.apply_invalidation(r)
        v2 = {r.rid: trf.check_semantics_II(r) for r in recs}
        n_bad2 = sum(1 for k in v2 if v2[k])
        tot2 = sum(len(x) for x in v2.values())
        n_inv = sum(1 for r in recs if r.iota is not None)
        results[label] = (n_bad, tot, cor12, n_inv, n_bad2, tot2)

    print("\n" + "-" * 74)
    hdr = f"{'measure':<42}{'constructed':>15}{'synthea':>15}"
    print(hdr); print("-" * 74)
    names = ["Semantics I: records with violation",
             "Semantics I: total violations",
             "Corollary 1.2 witnesses (no request)",
             "Records invalidated",
             "Semantics II: records with violation",
             "Semantics II: total violations"]
    identical = True
    for i, nm in enumerate(names):
        a, b = results["constructed"][i], results["synthea"][i]
        flag = "" if a == b else "   <-- DIFFERS"
        if a != b:
            identical = False
        print(f"{nm:<42}{a:>15}{b:>15}{flag}")
    print("-" * 74)

    # commitments must differ - different payloads, same salts
    diff_c = sum(1 for x, y in zip(base, real) if x.c != y.c)
    print(f"\ncommitments differing between the two runs: {diff_c}/{len(base)}"
          f"   (expected {len(base)} — same salt, different payload)")

    print("\n" + "=" * 74)
    if identical and diff_c == len(base):
        print("RESULT: every reported figure is IDENTICAL under real FHIR payloads,".center(74))
        print("while every commitment differs. The model reads timing, not content.".center(74))
    else:
        print("RESULT: DIVERGENCE DETECTED — investigate before reporting.".center(74))
    print("=" * 74)


if __name__ == "__main__":
    main()
